### ISSUE TITLE
Add `sensitive` property to templates`

### ISSUE THREAD

**Issue by ianbamforth** [tablexi/chef-sendmail-ses#13]
Just a suggestion as I've never actually tried this, but currently username / password gets written to the logs.  Seems like this is bad, but by adding `sensitive true` to the template blocks you can avoid this.

**Comment by phoolish** [comment]
My only concern is backwards compatibility. When was that attribute introduced?

**Comment by ianbamforth** [comment]
http://blog.thefourthparty.com/chef-sensitive/ says in 11.12, although I didn't notice it until today!On 10 Feb 2017 8:25 p.m., Lloyd Philbrook <notifications@github.com> wrote:My only concern is backwards compatibility. When was that attribute introduced?

**Comment by phoolish** [comment]
Hmm, well that works for me.  If you generate a PR, I'll merge it.

**Comment by phoolish** [comment]
Resolved by #18
