### ISSUE TITLE
Why the (implicit) delay on notify of template '/usr/share/sendmail-cf/ses/ses.cf' ?

### ISSUE THREAD

**Issue by ianbamforth** [tablexi/chef-sendmail-ses#4]
There's no action on the notify for this, so it defaults to "delayed".  Is there any reason for this?  My build process contains a reboot (for apt upgrade), which seems to be causing the action to be forgotten.

**Comment by phoolish** [comment]
I think it was incorrectly set.  I'd accept a PR with an update.

**Comment by phoolish** [comment]
Fixed with #8
