### ISSUE TITLE
Directory location should be configurable or changed to suit the OS

### ISSUE THREAD

**Issue by ianbamforth** [tablexi/chef-sendmail-ses#5]
The creation of the directory /usr/share/sendmail-cf/ses fails on Ubuntu, as /usr/share/sendmail-cf doesn't exist - it appears that the Ubuntu install of sendmail creates /usr/share/sendmail/cf instead.  I'd suggest one of the following:
1. create the dir recursively
2. make it a configurable thing
3. detect the os and set the directory accordingly

**Comment by phoolish** [comment]
This cookbook was setup for RHEL distros.  We do not use debian distros at work, so the functionality was never added.  I'd be open to a PR with those changes.

**Comment by plainlystated** [comment]
I'm also hitting this issue...

**Comment by phoolish** [comment]
Should be fixed with #8 and #9
